// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://agyxtvarmnpxqvsdiejm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFneXh0dmFybW5weHF2c2RpZWptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyODMxMzAsImV4cCI6MjA1OTg1OTEzMH0.DmFDI2lSBkLTE3o2sl-B9T4SYTOXqz8TpbbVqVgiQnk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);